### ISSUE TITLE
Specific node size tree

### ISSUE THREAD

**Issue by HHMagnus** [Nhartwig/dtu-applied-functional-programming#11]

**Comment by fabio-oesch** [comment]
Can only create easy trees for the time being. Meaning that it is only one node per level. Created also a batch tree creation. So we can create insert a list with various sizes and returns a list of trees with specific sizes.

**Comment by HHMagnus** [comment]
That seems fine

The function randomSquareTree width depth will generate a random tree of a specific size: *width* * *depth*

I'm going to close this, feel free to reopen if you don't think its done
