### ISSUE TITLE
Multiline post script

### ISSUE THREAD

**Issue by fabio-oesch** [Nhartwig/dtu-applied-functional-programming#5]
Tree looks shit make better

**Comment by HHMagnus** [comment]
The issue is still to prevent overlapping. But we talked to Michael and decided that we are going to make multilines for large text sizes. 

We then need to also consider the nodes further down. 
We decided the notes at a specific depth always have to be at the same y position

**Comment by HHMagnus** [comment]
This part is implemented in the latest push
