### ISSUE TITLE
Square tree generation

### ISSUE THREAD

**Issue by Nhartwig** [Nhartwig/dtu-applied-functional-programming#6]
Write functions to generate trees of different sizes for part 4.) of project

**Comment by HHMagnus** [comment]
I made a function called:
randomSquareTree width depth
Which generates a random square, but it's not exactly a square. It will have *width* nodes in each layer and a total depth of *depth*. I used the matrix method I tried to explain yesterday, where you randomize a matrix and use it to generate the tree.

**Comment by Nhartwig** [comment]
looks good!
